title: Blog
description: Rascunhos sobre matemática, física, data science e programação
baseurl: "/blog"
url: "https://joaofaugusto.github.io"

theme: minima

markdown: kramdown
kramdown:
  math_engine: mathjax
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate-v2

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post